{
    "license": "LGPL-3",
    "name": 'Threshold Report',
    'version': '17.0.1.0.2',
    'category': 'Accounting',
    'summary': 'Financial Security Threshold Report',
    'author': 'Your Company',
    'depends': ['account', 'base', 'purchase', 'sale', 'sale_purchase'],
    'data': [
        'security/ir.model.access.csv',
        'security/threshold_report_rules.xml',
        'views/threshold_report_wizard_view.xml',
        'views/threshold_report_account_mapping_views.xml',
        'views/menu_views.xml',
        'views/res_cpmpany_views_ext.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}