from odoo import models, fields, api
from odoo.exceptions import UserError
from datetime import datetime, date
from dateutil.relativedelta import relativedelta
import io
import xlsxwriter
import base64


class InvoiceComparisonWizard(models.TransientModel):
    _name = 'invoice.comparison.wizard'
    _description = 'Invoice Comparison Wizard'

    report_type = fields.Selection([
        ('yearly', 'Yearly'),
        ('monthly', 'Monthly')
    ], string='Report Type', required=True, default='yearly')
    years_count = fields.Selection([
        ('2', '2 Years'),
        ('3', '3 Years'),
        ('4', '4 Years'),
        ('5', '5 Years')
    ], string='Number of Years', required=True, default='3')
    company_ids = fields.Many2many('res.company', string='Companies')
    month = fields.Selection([
        ('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'),
        ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'),
        ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')
    ], string='Month')

    @api.onchange('report_type')
    def _onchange_report_type(self):
        if self.report_type != 'monthly': self.month = False

    def action_download_excel(self):
        if self.report_type == 'monthly' and not self.month:
            raise UserError('Please select a month for monthly report.')

        if self.report_type == 'yearly':
            data = self._get_yearly_data()
            return self._download_yearly_excel(data)
        else:
            data = self._get_monthly_data()
            return self._download_monthly_excel(data)

    def _download_yearly_excel(self, data):
        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output)
        worksheet = workbook.add_worksheet('Invoice Comparison')

        # Professional Formats
        title_format = workbook.add_format({
            'bold': True, 'font_size': 18, 'align': 'center',
            'font_color': '#FFFFFF', 'bg_color': '#2E5984',
            'border': 2, 'border_color': '#1F4E79'
        })

        company_section_format = workbook.add_format({
            'bold': True, 'font_size': 12, 'align': 'left',
            'font_color': '#2E5984', 'bg_color': '#E8F1FF',
            'border': 1, 'border_color': '#B8D4F0'
        })

        info_format = workbook.add_format({
            'font_size': 9, 'align': 'left', 'italic': True,
            'font_color': '#666666'
        })

        header_format = workbook.add_format({
            'bold': True, 'font_size': 10, 'align': 'center',
            'font_color': '#FFFFFF', 'bg_color': '#4A90C2',
            'border': 1, 'border_color': '#2E5984'
        })

        data_format = workbook.add_format({
            'border': 1, 'num_format': '#,##0.00', 'align': 'right',
            'border_color': '#D0D0D0', 'font_size': 9
        })

        percent_format = workbook.add_format({
            'border': 1, 'num_format': '0.00%', 'align': 'right',
            'font_color': '#E67E22', 'bg_color': '#FDF2E9',
            'border_color': '#D0D0D0', 'bold': True, 'font_size': 9
        })

        customer_format = workbook.add_format({
            'border': 1, 'align': 'left', 'font_size': 9,
            'border_color': '#D0D0D0'
        })

        years = data['years']
        companies = data['companies']
        current_year = datetime.now().year

        # Calculate total columns needed - invoices, growth %, then budgets
        total_cols = 1 + len(years) + (len(years) - 1)  # Customer + years + growth columns
        budget_years = [year for year in years if year >= current_year]
        total_cols += len(budget_years)  # Budget columns

        # Main Title
        worksheet.merge_range(1, 0, 2, total_cols - 1, 'INVOICE COMPARISON REPORT - YEARLY', title_format)

        # Report Info with better spacing
        worksheet.write(4, 0, f'Generated By: {self.env.user.name}', info_format)
        worksheet.write(4, max(4, total_cols - 3), f'Date: {datetime.now().strftime("%B %d, %Y at %H:%M")}',
                        info_format)

        # Headers with better styling
        col = 0
        worksheet.write(6, col, 'Customer', header_format)
        col += 1

        # First write all year columns (invoice data)
        for i, year in enumerate(years):
            worksheet.write(6, col, str(year), header_format)
            col += 1

            # Add Growth % column after each year except the first
            if i > 0:
                worksheet.write(6, col, f'Growth %', header_format)
                col += 1

        # Then write budget columns at the end
        for year in budget_years:
            worksheet.write(6, col, f'{year} Budget', header_format)
            col += 1

        # Data with alternating row colors
        row = 7
        first_company = True

        for company_name, customers in companies.items():
            if not first_company:
                row += 1  # Empty row between companies

            # Company section header
            worksheet.merge_range(row, 0, row, total_cols - 1, f'🏢 {company_name}', company_section_format)
            row += 1

            # Alternating row colors for customers
            customer_count = 0
            for customer, year_data in customers.items():
                col = 0

                # Check if new customer (0 amount in second last year)
                second_last_year_data = year_data.get(years[-2], {'invoice': 0, 'budget': 0, 'total': 0})
                if isinstance(second_last_year_data, dict):
                    second_last_year_total = second_last_year_data['total']
                else:
                    second_last_year_total = second_last_year_data

                is_new_customer = second_last_year_total == 0

                # Set row background - yellow for new customers, alternating for others
                if is_new_customer:
                    row_format = workbook.add_format({
                        'border': 1, 'align': 'left', 'font_size': 9,
                        'border_color': '#D0D0D0', 'bg_color': '#FFFF99'
                    })
                    data_row_format = workbook.add_format({
                        'border': 1, 'num_format': '#,##0.00', 'align': 'right',
                        'border_color': '#D0D0D0', 'font_size': 9, 'bg_color': '#FFFF99'
                    })
                elif customer_count % 2 == 0:
                    row_format = workbook.add_format({
                        'border': 1, 'align': 'left', 'font_size': 9,
                        'border_color': '#D0D0D0', 'bg_color': '#F8F9FA'
                    })
                    data_row_format = workbook.add_format({
                        'border': 1, 'num_format': '#,##0.00', 'align': 'right',
                        'border_color': '#D0D0D0', 'font_size': 9, 'bg_color': '#F8F9FA'
                    })
                else:
                    row_format = customer_format
                    data_row_format = data_format

                worksheet.write(row, col, customer, row_format)
                col += 1

                # First write all year data (invoice/total amounts)
                year_totals = []
                year_budgets = {}

                for i, year in enumerate(years):
                    year_data_item = year_data.get(year, {'invoice': 0, 'budget': 0, 'total': 0})

                    # Handle both dict and float formats
                    if isinstance(year_data_item, dict):
                        year_total = year_data_item['total']
                        year_invoice = year_data_item['invoice']
                        year_budget = year_data_item['budget']
                    else:
                        year_total = year_data_item
                        year_invoice = year_data_item
                        year_budget = 0

                    year_totals.append(year_total)
                    if year >= current_year:
                        year_budgets[year] = year_budget

                    # Write year data (for current/future years, use invoice amount only)
                    if year >= current_year:
                        worksheet.write(row, col, year_invoice, data_row_format)
                    else:
                        worksheet.write(row, col, year_total, data_row_format)
                    col += 1

                    # Add Growth % column after each year except the first
                    if i > 0:
                        prev_total = year_totals[i - 1]
                        curr_total = year_totals[i]
                        diff = ((curr_total - prev_total) / prev_total) if prev_total != 0 else (
                            1 if curr_total > 0 else 0)
                        worksheet.write(row, col, diff, percent_format)
                        col += 1

                # Then write budget columns at the end
                budget_format = workbook.add_format({
                    'border': 1, 'num_format': '#,##0.00', 'align': 'right',
                    'border_color': '#D0D0D0', 'font_size': 9,
                    'bg_color': '#FFFF99' if is_new_customer else ('#E8F4FD' if customer_count % 2 == 0 else '#FFFFFF')
                })

                for year in [y for y in years if y >= current_year]:
                    budget_amount = year_budgets.get(year, 0)
                    worksheet.write(row, col, budget_amount if budget_amount > 0 else 0, budget_format)
                    col += 1

                row += 1
                customer_count += 1

            first_company = False

        # Professional column widths
        worksheet.set_column('A:A', 28)
        worksheet.set_column(1, total_cols - 1, 14)

        # Add footer
        worksheet.write(row + 2, 0, 'Generated by Odoo Invoice Reporting Module', info_format)

        workbook.close()
        output.seek(0)

        attachment = self.env['ir.attachment'].create({
            'name': f'Invoice_Comparison_yearly_{datetime.now().strftime("%Y%m%d")}.xlsx',
            'type': 'binary',
            'datas': base64.b64encode(output.read()),
            'res_model': self._name,
            'res_id': self.id,
            'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        })

        return {
            'type': 'ir.actions.act_url',
            'url': f'/web/content/{attachment.id}?download=true',
            'target': 'self',
        }

    def _download_monthly_excel(self, data):
        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output)
        worksheet = workbook.add_worksheet('Invoice Comparison')

        # Professional Formats (same as yearly)
        title_format = workbook.add_format({
            'bold': True, 'font_size': 18, 'align': 'center',
            'font_color': '#FFFFFF', 'bg_color': '#2E5984',
            'border': 2, 'border_color': '#1F4E79'
        })

        company_section_format = workbook.add_format({
            'bold': True, 'font_size': 12, 'align': 'left',
            'font_color': '#2E5984', 'bg_color': '#E8F1FF',
            'border': 1, 'border_color': '#B8D4F0'
        })

        info_format = workbook.add_format({
            'font_size': 9, 'align': 'left', 'italic': True,
            'font_color': '#666666'
        })

        header_format = workbook.add_format({
            'bold': True, 'font_size': 10, 'align': 'center',
            'font_color': '#FFFFFF', 'bg_color': '#4A90C2',
            'border': 1, 'border_color': '#2E5984'
        })

        data_format = workbook.add_format({
            'border': 1, 'num_format': '#,##0.00', 'align': 'right',
            'border_color': '#D0D0D0', 'font_size': 9
        })

        percent_format = workbook.add_format({
            'border': 1, 'num_format': '0.00%', 'align': 'right',
            'font_color': '#E67E22', 'bg_color': '#FDF2E9',
            'border_color': '#D0D0D0', 'bold': True, 'font_size': 9
        })

        customer_format = workbook.add_format({
            'border': 1, 'align': 'left', 'font_size': 9,
            'border_color': '#D0D0D0'
        })

        month_names = ['', 'January', 'February', 'March', 'April', 'May', 'June',
                       'July', 'August', 'September', 'October', 'November', 'December']

        years = data['years']
        companies = data['companies']
        current_year = datetime.now().year

        # Calculate total columns needed - invoices, growth %, then budgets
        total_cols = 1 + len(years) + (len(years) - 1)  # Customer + years + growth columns
        budget_years = [year for year in years if year >= current_year]
        total_cols += len(budget_years)  # Budget columns

        # Main Title
        worksheet.merge_range(1, 0, 2, total_cols - 1,
                              f'INVOICE COMPARISON REPORT - {month_names[int(self.month)].upper()}', title_format)

        # Report Info
        worksheet.write(4, 0, f'Generated By: {self.env.user.name}', info_format)
        worksheet.write(4, max(4, total_cols - 3), f'Date: {datetime.now().strftime("%B %d, %Y at %H:%M")}',
                        info_format)

        # Headers
        col = 0
        worksheet.write(6, col, 'Customer', header_format)
        col += 1

        month_short = month_names[int(self.month)][:3]
        # First write all year columns
        for i, year in enumerate(years):
            worksheet.write(6, col, f'{month_short} {year}', header_format)
            col += 1

            # Add Growth % column after each year except the first
            if i > 0:
                worksheet.write(6, col, f'Growth %', header_format)
                col += 1

        # Then write budget columns at the end
        for year in budget_years:
            worksheet.write(6, col, f'{month_short} {year} Budget', header_format)
            col += 1

        # Data with same styling as yearly
        row = 7
        first_company = True

        for company_name, customers in companies.items():
            if not first_company:
                row += 1

            worksheet.merge_range(row, 0, row, total_cols - 1, f'🏢 {company_name}', company_section_format)
            row += 1

            customer_count = 0
            for customer, year_data in customers.items():
                col = 0

                # Check if new customer (0 amount in second last year)
                second_last_year_data = year_data.get(years[-2], {'invoice': 0, 'budget': 0, 'total': 0})
                if isinstance(second_last_year_data, dict):
                    second_last_year_total = second_last_year_data['total']
                else:
                    second_last_year_total = second_last_year_data

                is_new_customer = second_last_year_total == 0

                # Set row background - yellow for new customers, alternating for others
                if is_new_customer:
                    row_format = workbook.add_format({
                        'border': 1, 'align': 'left', 'font_size': 9,
                        'border_color': '#D0D0D0', 'bg_color': '#FFFF99'
                    })
                    data_row_format = workbook.add_format({
                        'border': 1, 'num_format': '#,##0.00', 'align': 'right',
                        'border_color': '#D0D0D0', 'font_size': 9, 'bg_color': '#FFFF99'
                    })
                elif customer_count % 2 == 0:
                    row_format = workbook.add_format({
                        'border': 1, 'align': 'left', 'font_size': 9,
                        'border_color': '#D0D0D0', 'bg_color': '#F8F9FA'
                    })
                    data_row_format = workbook.add_format({
                        'border': 1, 'num_format': '#,##0.00', 'align': 'right',
                        'border_color': '#D0D0D0', 'font_size': 9, 'bg_color': '#F8F9FA'
                    })
                else:
                    row_format = customer_format
                    data_row_format = data_format

                worksheet.write(row, col, customer, row_format)
                col += 1

                # First write all year data (invoice/total amounts)
                year_totals = []
                year_budgets = {}

                for i, year in enumerate(years):
                    year_data_item = year_data.get(year, {'invoice': 0, 'budget': 0, 'total': 0})

                    # Handle both dict and float formats
                    if isinstance(year_data_item, dict):
                        year_total = year_data_item['total']
                        year_invoice = year_data_item['invoice']
                        year_budget = year_data_item['budget']
                    else:
                        year_total = year_data_item
                        year_invoice = year_data_item
                        year_budget = 0

                    year_totals.append(year_total)
                    if year >= current_year:
                        year_budgets[year] = year_budget

                    # Write year data (for current/future years, use invoice amount only)
                    if year >= current_year:
                        worksheet.write(row, col, year_invoice, data_row_format)
                    else:
                        worksheet.write(row, col, year_total, data_row_format)
                    col += 1

                    # Add Growth % column after each year except the first
                    if i > 0:
                        prev_total = year_totals[i - 1]
                        curr_total = year_totals[i]
                        diff = ((curr_total - prev_total) / prev_total) if prev_total != 0 else (
                            1 if curr_total > 0 else 0)
                        worksheet.write(row, col, diff, percent_format)
                        col += 1

                # Then write budget columns at the end
                budget_format = workbook.add_format({
                    'border': 1, 'num_format': '#,##0.00', 'align': 'right',
                    'border_color': '#D0D0D0', 'font_size': 9,
                    'bg_color': '#FFFF99' if is_new_customer else ('#E8F4FD' if customer_count % 2 == 0 else '#FFFFFF')
                })

                for year in [y for y in years if y >= current_year]:
                    budget_amount = year_budgets.get(year, 0)
                    worksheet.write(row, col, budget_amount if budget_amount > 0 else 0, budget_format)
                    col += 1

                row += 1
                customer_count += 1

            first_company = False

        worksheet.set_column('A:A', 28)
        worksheet.set_column(1, total_cols - 1, 14)
        worksheet.write(row + 2, 0, 'Generated by Odoo Invoice Reporting Module', info_format)

        workbook.close()
        output.seek(0)

        attachment = self.env['ir.attachment'].create({
            'name': f'Invoice_Comparison_{month_names[int(self.month)]}_{datetime.now().strftime("%Y%m%d")}.xlsx',
            'type': 'binary',
            'datas': base64.b64encode(output.read()),
            'res_model': self._name,
            'res_id': self.id,
            'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        })

        return {
            'type': 'ir.actions.act_url',
            'url': f'/web/content/{attachment.id}?download=true',
            'target': 'self',
        }

    def _get_yearly_data(self):
        current_year = datetime.now().year
        years_count = int(self.years_count)
        years = [current_year - years_count + 1 + i for i in range(years_count)]

        # Get ALL company partners to exclude
        all_company_partners = self.env['res.company'].search([]).mapped('partner_id.id')

        # Get all customers from invoices
        invoice_domain = [
            ('move_type', '=', 'out_invoice'),
            ('state', '=', 'posted'),
            ('invoice_date', '>=', date(years[0], 1, 1)),
            ('invoice_date', '<=', date(years[-1], 12, 31)),
            ('partner_id', 'not in', all_company_partners),
            ('partner_id.active', '=', True)
        ]

        if self.company_ids:
            invoice_domain.append(('company_id', 'in', self.company_ids.ids))

        invoices = self.env['account.move'].sudo().search(invoice_domain)

        # Get all customers from budget lines
        budget_domain = [
            ('date_from', '<=', date(years[-1], 12, 31)),
            ('date_to', '>=', date(years[0], 1, 1)),
            ('planned_amount', '>', 0),
            ('analytic_account_id.partner_id', 'not in', all_company_partners),
            ('analytic_account_id.partner_id.active', '=', True)
        ]

        if self.company_ids:
            budget_domain.append(('analytic_account_id.company_id', 'in', self.company_ids.ids))

        budget_lines = self.env['crossovered.budget.lines'].sudo().search(budget_domain)
        budget_lines = budget_lines.filtered(
            lambda rec: rec.crossovered_budget_id.state in ['confirm', 'validate', 'done'])

        # Collect all unique customers
        all_customers = set()

        # Add customers from invoices
        for invoice in invoices:
            if invoice.invoice_date:
                all_customers.add((invoice.company_id.id, invoice.partner_id.id, invoice.company_id.name,
                                   invoice.partner_id.name or invoice.partner_id.display_name or 'Unknown Customer'))

        # Add customers from budget lines
        for budget_line in budget_lines:
            if budget_line.analytic_account_id.partner_id:
                all_customers.add(
                    (budget_line.analytic_account_id.company_id.id, budget_line.analytic_account_id.partner_id.id,
                     budget_line.analytic_account_id.company_id.name,
                     budget_line.analytic_account_id.partner_id.name or budget_line.analytic_account_id.partner_id.display_name or 'Unknown Customer'))

        # Group by company and customer, then calculate combined amounts
        company_data = {}

        for company_id, partner_id, company_name, customer_name in all_customers:
            if company_name not in company_data:
                company_data[company_name] = {}
            if customer_name not in company_data[company_name]:
                company_data[company_name][customer_name] = {}

            # Calculate combined amounts for all years using month checking logic
            for year in years:
                if year < current_year:
                    # Past year - only invoice data
                    total_amount = 0.0
                    for month in range(1, 13):
                        amount = self._get_customer_actual_for_month(partner_id, company_id, year, month)
                        total_amount += amount
                    company_data[company_name][customer_name][year] = total_amount
                else:
                    # Current/future year - separate invoice and budget
                    invoice_amount = 0.0
                    budget_amount = 0.0

                    for month in range(1, 13):
                        target_month_end = date(year, month, 1) + relativedelta(months=1) - relativedelta(days=1)
                        current_date = fields.Date.today()

                        if (year, month) <= (current_date.year, current_date.month):
                            # Past month - use actual
                            amount = self._get_customer_actual_for_month(partner_id, company_id, year, month)
                            invoice_amount += amount
                        else:
                            # Future month - use budget
                            amount = self._get_customer_budget_for_month(partner_id, company_id, year, month)
                            budget_amount += amount

                    company_data[company_name][customer_name][year] = {
                        'invoice': invoice_amount,
                        'budget': budget_amount,
                        'total': invoice_amount + budget_amount
                    }

        return {'years': years, 'companies': company_data}

    def _get_customer_amount_for_month(self, customer_id, company_id, year, month):
        # Check if the entire month has passed
        target_month_end = date(year, month, 1) + relativedelta(months=1) - relativedelta(days=1)
        current_date = fields.Date.today()

        if target_month_end < current_date:
            # Month has passed - get actual invoices
            return self._get_customer_actual_for_month(customer_id, company_id, year, month)
        else:
            # Future month - get budget
            return self._get_customer_budget_for_month(customer_id, company_id, year, month)

    def _get_customer_actual_for_month(self, customer_id, company_id, year, month):
        start_date = date(year, month, 1)
        end_date = (start_date + relativedelta(months=1)) - relativedelta(days=1)

        invoices = self.env['account.move'].sudo().search([
            ('partner_id', '=', customer_id),
            ('company_id', '=', company_id),
            ('move_type', '=', 'out_invoice'),
            ('state', '=', 'posted'),
            ('invoice_date', '>=', start_date),
            ('invoice_date', '<=', end_date)
        ])

        return sum(invoices.mapped('amount_total_signed'))

    def _get_customer_budget_for_month(self, customer_id, company_id, year, month):
        analytic_account = self.env['account.analytic.account'].search([
            ('partner_id', '=', customer_id),
            ('company_id', '=', company_id)
        ], limit=1)

        if not analytic_account:
            return 0.0

        # Find sales budget posts (revenue accounts)
        sales_budget_posts = self.env['account.budget.post'].search([
            ('account_ids.account_type', '=', 'income'),
            ('company_id', '=', company_id)
        ])

        if not sales_budget_posts:
            return 0.0

        start_date = date(year, month, 1)
        end_date = (start_date + relativedelta(months=1)) - relativedelta(days=1)

        budget_lines = self.env['crossovered.budget.lines'].search([
            ('analytic_account_id', '=', analytic_account.id),
            ('general_budget_id', 'in', sales_budget_posts.ids),
            ('date_from', '<=', end_date),
            ('date_to', '>=', start_date),
            ('planned_amount', '>', 0)
        ])
        if budget_lines:
            budget_lines = budget_lines.filtered(
                lambda rec: rec.crossovered_budget_id.state in ['confirm', 'validate', 'done'])

        total_budget = 0.0
        for line in budget_lines:
            line_start = max(line.date_from, start_date)
            line_end = min(line.date_to, end_date)

            if line_start <= line_end:
                line_days = (line.date_to - line.date_from).days + 1
                month_days = (line_end - line_start).days + 1
                proportion = month_days / line_days
                total_budget += line.planned_amount * proportion

        return total_budget

    def _get_monthly_data(self):
        current_year = datetime.now().year
        years_count = int(self.years_count)
        years = [current_year - years_count + 1 + i for i in range(years_count)]
        month_int = int(self.month)

        # Get all customers from invoices in the date range
        start_date = date(years[0], month_int, 1)
        end_date = (date(years[-1], month_int, 1) + relativedelta(months=1)) - relativedelta(days=1)

        # Get ALL company partners to exclude
        all_company_partners = self.env['res.company'].search([]).mapped('partner_id.id')

        domain = [
            ('move_type', '=', 'out_invoice'),
            ('state', '=', 'posted'),
            ('invoice_date', '>=', start_date),
            ('invoice_date', '<=', end_date),
            ('partner_id', 'not in', all_company_partners),
            ('partner_id.active', '=', True)
        ]

        if self.company_ids:
            domain.append(('company_id', 'in', self.company_ids.ids))

        invoices = self.env['account.move'].sudo().search(domain)

        # Group by company and customer, then get amounts (actual or budget)
        company_data = {}
        processed_customers = set()

        for invoice in invoices:
            if not invoice.invoice_date or invoice.invoice_date.month != month_int:
                continue

            company = invoice.company_id.name
            customer = invoice.partner_id.name or invoice.partner_id.display_name or 'Unknown Customer'
            customer_key = (invoice.company_id.id, invoice.partner_id.id, customer)

            if company not in company_data:
                company_data[company] = {}
            if customer not in company_data[company]:
                company_data[company][customer] = {}

            if customer_key not in processed_customers:
                # Get amounts for all years (actual or budget)
                for year in years:
                    if year < current_year:
                        # Past year - only invoice data
                        amount = self._get_customer_actual_for_month(
                            invoice.partner_id.id, invoice.company_id.id, year, month_int
                        )
                        company_data[company][customer][year] = amount
                    else:
                        # Current/future year - separate invoice and budget
                        target_month_end = date(year, month_int, 1) + relativedelta(months=1) - relativedelta(days=1)
                        current_date = fields.Date.today()

                        if (year, month_int) <= (current_date.year, current_date.month):
                            # Past month - use actual
                            invoice_amount = self._get_customer_actual_for_month(
                                invoice.partner_id.id, invoice.company_id.id, year, month_int
                            )
                            budget_amount = 0
                        else:
                            # Future month - use budget
                            invoice_amount = 0
                            budget_amount = self._get_customer_budget_for_month(
                                invoice.partner_id.id, invoice.company_id.id, year, month_int
                            )

                        company_data[company][customer][year] = {
                            'invoice': invoice_amount,
                            'budget': budget_amount,
                            'total': invoice_amount + budget_amount
                        }

                processed_customers.add(customer_key)

        return {'years': years, 'companies': company_data}