from odoo import models, fields, api
from odoo.exceptions import UserError
from datetime import datetime, date
from dateutil.relativedelta import relativedelta
import io
import xlsxwriter
import base64


class InvoiceComparisonWizard(models.TransientModel):
    _name = 'invoice.comparison.wizard'
    _description = 'Invoice Comparison Wizard'

    report_type = fields.Selection([
        ('yearly', 'Yearly'),
        ('monthly', 'Monthly')
    ], string='Report Type', required=True, default='yearly')
    
    years_count = fields.Selection([
        ('2', '2 Years'),
        ('3', '3 Years'),
        ('4', '4 Years'),
        ('5', '5 Years')
    ], string='Number of Years', required=True, default='3')
    
    company_ids = fields.Many2many('res.company', string='Companies')
    
    month = fields.Selection([
        ('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'),
        ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'),
        ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')
    ], string='Month')
    
    @api.onchange('report_type')
    def _onchange_report_type(self):
        if self.report_type != 'monthly':
            self.month = False

    def action_download_excel(self):
        if self.report_type == 'monthly' and not self.month:
            raise UserError('Please select a month for monthly report.')
        
        if self.report_type == 'yearly':
            data = self._get_yearly_data()
            return self._download_yearly_excel(data)
        else:
            data = self._get_monthly_data()
            return self._download_monthly_excel(data)
    
    def _download_yearly_excel(self, data):
        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output)
        worksheet = workbook.add_worksheet('Invoice Comparison')
        
        # Professional Formats
        title_format = workbook.add_format({
            'bold': True, 'font_size': 18, 'align': 'center', 
            'font_color': '#FFFFFF', 'bg_color': '#2E5984',
            'border': 2, 'border_color': '#1F4E79'
        })
        
        company_section_format = workbook.add_format({
            'bold': True, 'font_size': 12, 'align': 'left',
            'font_color': '#2E5984', 'bg_color': '#E8F1FF',
            'border': 1, 'border_color': '#B8D4F0'
        })
        
        info_format = workbook.add_format({
            'font_size': 9, 'align': 'left', 'italic': True,
            'font_color': '#666666'
        })
        
        header_format = workbook.add_format({
            'bold': True, 'font_size': 10, 'align': 'center',
            'font_color': '#FFFFFF', 'bg_color': '#4A90C2',
            'border': 1, 'border_color': '#2E5984'
        })
        
        data_format = workbook.add_format({
            'border': 1, 'num_format': '#,##0.00', 'align': 'right',
            'border_color': '#D0D0D0', 'font_size': 9
        })
        
        percent_format = workbook.add_format({
            'border': 1, 'num_format': '0.00%', 'align': 'right',
            'font_color': '#E67E22', 'bg_color': '#FDF2E9',
            'border_color': '#D0D0D0', 'bold': True, 'font_size': 9
        })
        
        customer_format = workbook.add_format({
            'border': 1, 'align': 'left', 'font_size': 9,
            'border_color': '#D0D0D0'
        })
        
        years = data['years']
        companies = data['companies']
        
        # Calculate total columns needed
        total_cols = 1 + (len(years) - 1) * 3
        
        # Main Title
        worksheet.merge_range(1, 0, 2, total_cols - 1, 'INVOICE COMPARISON REPORT - YEARLY', title_format)
        
        # Report Info with better spacing
        worksheet.write(4, 0, f'Generated By: {self.env.user.name}', info_format)
        worksheet.write(4, max(4, total_cols - 3), f'Date: {datetime.now().strftime("%B %d, %Y at %H:%M")}', info_format)
        
        # Headers with better styling
        col = 0
        worksheet.write(6, col, 'Customer', header_format)
        col += 1
        
        for i in range(len(years) - 1):
            worksheet.write(6, col, str(years[i]), header_format)
            col += 1
            worksheet.write(6, col, str(years[i+1]), header_format)
            col += 1
            worksheet.write(6, col, f'Growth %', header_format)
            col += 1
        
        # Data with alternating row colors
        row = 7
        first_company = True
        
        for company_name, customers in companies.items():
            if not first_company:
                row += 1  # Empty row between companies
            
            # Company section header
            worksheet.merge_range(row, 0, row, total_cols - 1, f'🏢 {company_name}', company_section_format)
            row += 1
            
            # Alternating row colors for customers
            customer_count = 0
            for customer, year_data in customers.items():
                col = 0
                
                # Alternate row background
                if customer_count % 2 == 0:
                    row_format = workbook.add_format({
                        'border': 1, 'align': 'left', 'font_size': 9,
                        'border_color': '#D0D0D0', 'bg_color': '#F8F9FA'
                    })
                    data_row_format = workbook.add_format({
                        'border': 1, 'num_format': '#,##0.00', 'align': 'right',
                        'border_color': '#D0D0D0', 'font_size': 9, 'bg_color': '#F8F9FA'
                    })
                else:
                    row_format = customer_format
                    data_row_format = data_format
                
                worksheet.write(row, col, customer, row_format)
                col += 1
                
                amounts = [year_data.get(year, 0) for year in years]
                
                for i in range(len(amounts) - 1):
                    worksheet.write(row, col, amounts[i], data_row_format)
                    col += 1
                    worksheet.write(row, col, amounts[i + 1], data_row_format)
                    col += 1
                    prev_amt = amounts[i]
                    curr_amt = amounts[i + 1]
                    diff = ((curr_amt - prev_amt) / prev_amt) if prev_amt != 0 else (1 if curr_amt > 0 else 0)
                    worksheet.write(row, col, diff, percent_format)
                    col += 1
                
                row += 1
                customer_count += 1
            
            first_company = False
        
        # Professional column widths
        worksheet.set_column('A:A', 28)
        worksheet.set_column(1, total_cols - 1, 14)
        
        # Add footer
        worksheet.write(row + 2, 0, 'Generated by Odoo Invoice Reporting Module', info_format)
        
        workbook.close()
        output.seek(0)
        
        attachment = self.env['ir.attachment'].create({
            'name': f'Invoice_Comparison_yearly_{datetime.now().strftime("%Y%m%d")}.xlsx',
            'type': 'binary',
            'datas': base64.b64encode(output.read()),
            'res_model': self._name,
            'res_id': self.id,
            'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        })
        
        return {
            'type': 'ir.actions.act_url',
            'url': f'/web/content/{attachment.id}?download=true',
            'target': 'self',
        }
    
    def _download_monthly_excel(self, data):
        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output)
        worksheet = workbook.add_worksheet('Invoice Comparison')
        
        # Professional Formats (same as yearly)
        title_format = workbook.add_format({
            'bold': True, 'font_size': 18, 'align': 'center', 
            'font_color': '#FFFFFF', 'bg_color': '#2E5984',
            'border': 2, 'border_color': '#1F4E79'
        })
        
        company_section_format = workbook.add_format({
            'bold': True, 'font_size': 12, 'align': 'left',
            'font_color': '#2E5984', 'bg_color': '#E8F1FF',
            'border': 1, 'border_color': '#B8D4F0'
        })
        
        info_format = workbook.add_format({
            'font_size': 9, 'align': 'left', 'italic': True,
            'font_color': '#666666'
        })
        
        header_format = workbook.add_format({
            'bold': True, 'font_size': 10, 'align': 'center',
            'font_color': '#FFFFFF', 'bg_color': '#4A90C2',
            'border': 1, 'border_color': '#2E5984'
        })
        
        data_format = workbook.add_format({
            'border': 1, 'num_format': '#,##0.00', 'align': 'right',
            'border_color': '#D0D0D0', 'font_size': 9
        })
        
        percent_format = workbook.add_format({
            'border': 1, 'num_format': '0.00%', 'align': 'right',
            'font_color': '#E67E22', 'bg_color': '#FDF2E9',
            'border_color': '#D0D0D0', 'bold': True, 'font_size': 9
        })
        
        customer_format = workbook.add_format({
            'border': 1, 'align': 'left', 'font_size': 9,
            'border_color': '#D0D0D0'
        })
        
        month_names = ['', 'January', 'February', 'March', 'April', 'May', 'June',
                      'July', 'August', 'September', 'October', 'November', 'December']
        
        years = data['years']
        companies = data['companies']
        
        total_cols = 1 + (len(years) - 1) * 3
        
        # Main Title
        worksheet.merge_range(1, 0, 2, total_cols - 1, f'INVOICE COMPARISON REPORT - {month_names[int(self.month)].upper()}', title_format)
        
        # Report Info
        worksheet.write(4, 0, f'Generated By: {self.env.user.name}', info_format)
        worksheet.write(4, max(4, total_cols - 3), f'Date: {datetime.now().strftime("%B %d, %Y at %H:%M")}', info_format)
        
        # Headers
        col = 0
        worksheet.write(6, col, 'Customer', header_format)
        col += 1
        
        month_short = month_names[int(self.month)][:3]
        for i in range(len(years) - 1):
            worksheet.write(6, col, f'{month_short} {years[i]}', header_format)
            col += 1
            worksheet.write(6, col, f'{month_short} {years[i+1]}', header_format)
            col += 1
            worksheet.write(6, col, f'Growth %', header_format)
            col += 1
        
        # Data with same styling as yearly
        row = 7
        first_company = True
        
        for company_name, customers in companies.items():
            if not first_company:
                row += 1
            
            worksheet.merge_range(row, 0, row, total_cols - 1, f'🏢 {company_name}', company_section_format)
            row += 1
            
            customer_count = 0
            for customer, year_data in customers.items():
                col = 0
                
                if customer_count % 2 == 0:
                    row_format = workbook.add_format({
                        'border': 1, 'align': 'left', 'font_size': 9,
                        'border_color': '#D0D0D0', 'bg_color': '#F8F9FA'
                    })
                    data_row_format = workbook.add_format({
                        'border': 1, 'num_format': '#,##0.00', 'align': 'right',
                        'border_color': '#D0D0D0', 'font_size': 9, 'bg_color': '#F8F9FA'
                    })
                else:
                    row_format = customer_format
                    data_row_format = data_format
                
                worksheet.write(row, col, customer, row_format)
                col += 1
                
                amounts = [year_data.get(year, 0) for year in years]
                
                for i in range(len(amounts) - 1):
                    worksheet.write(row, col, amounts[i], data_row_format)
                    col += 1
                    worksheet.write(row, col, amounts[i + 1], data_row_format)
                    col += 1
                    prev_amt = amounts[i]
                    curr_amt = amounts[i + 1]
                    diff = ((curr_amt - prev_amt) / prev_amt) if prev_amt != 0 else (1 if curr_amt > 0 else 0)
                    worksheet.write(row, col, diff, percent_format)
                    col += 1
                
                row += 1
                customer_count += 1
            
            first_company = False
        
        worksheet.set_column('A:A', 28)
        worksheet.set_column(1, total_cols - 1, 14)
        worksheet.write(row + 2, 0, 'Generated by Odoo Invoice Reporting Module', info_format)
        
        workbook.close()
        output.seek(0)
        
        attachment = self.env['ir.attachment'].create({
            'name': f'Invoice_Comparison_{month_names[int(self.month)]}_{datetime.now().strftime("%Y%m%d")}.xlsx',
            'type': 'binary',
            'datas': base64.b64encode(output.read()),
            'res_model': self._name,
            'res_id': self.id,
            'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        })
        
        return {
            'type': 'ir.actions.act_url',
            'url': f'/web/content/{attachment.id}?download=true',
            'target': 'self',
        }

    def _get_yearly_data(self):
        current_year = datetime.now().year
        years_count = int(self.years_count)
        years = [current_year - years_count + 1 + i for i in range(years_count)]
        
        domain = [
            ('move_type', '=', 'out_invoice'),
            ('state', '=', 'posted'),
            ('invoice_date', '>=', date(years[0], 1, 1)),
            ('invoice_date', '<=', date(years[-1], 12, 31))
        ]
        
        if self.company_ids:
            domain.append(('company_id', 'in', self.company_ids.ids))
        
        invoices = self.env['account.move'].sudo().search(domain)
        
        # Group by company, customer and year
        company_data = {}
        for invoice in invoices:
            if not invoice.invoice_date:
                continue
            year = invoice.invoice_date.year
            company = invoice.company_id.name
            customer = invoice.partner_id.name or invoice.partner_id.display_name or  'Unknown Customer'
            
            if company not in company_data:
                company_data[company] = {}
            if customer not in company_data[company]:
                company_data[company][customer] = {}
            if year not in company_data[company][customer]:
                company_data[company][customer][year] = 0
            company_data[company][customer][year] += invoice.amount_total_signed
        
        return {'years': years, 'companies': company_data}

    def _get_customer_amount_for_month(self, customer_id, company_id, year, month):
        target_date = date(year, month, 1)
        current_date = fields.Date.today()
        
        if target_date <= current_date:
            # Month has passed - get actual invoices
            start_date = date(year, month, 1)
            end_date = (start_date + relativedelta(months=1)) - relativedelta(days=1)
            
            invoices = self.env['account.move'].sudo().search([
                ('partner_id', '=', customer_id),
                ('company_id', '=', company_id),
                ('move_type', '=', 'out_invoice'),
                ('state', '=', 'posted'),
                ('invoice_date', '>=', start_date),
                ('invoice_date', '<=', end_date)
            ])
            
            return sum(invoices.mapped('amount_total_signed'))
        else:
            # Future month - get budget
            return self._get_customer_budget_for_month(customer_id, company_id, year, month)
    
    def _get_customer_budget_for_month(self, customer_id, company_id, year, month):
        analytic_account = self.env['account.analytic.account'].search([
            ('partner_id', '=', customer_id),
            ('company_id', '=', company_id)
        ], limit=1)
        
        if not analytic_account:
            return 0.0
        
        # Find sales budget posts (revenue accounts)
        sales_budget_posts = self.env['account.budget.post'].search([
            ('account_ids.account_type', '=', 'income'),
            ('company_id', '=', company_id)
        ])
        
        if not sales_budget_posts:
            return 0.0
        
        start_date = date(year, month, 1)
        end_date = (start_date + relativedelta(months=1)) - relativedelta(days=1)
        
        budget_lines = self.env['crossovered.budget.lines'].search([
            ('analytic_account_id', '=', analytic_account.id),
            ('general_budget_id', 'in', sales_budget_posts.ids),
            ('date_from', '<=', end_date),
            ('date_to', '>=', start_date),
            ('crossovered_budget_state', 'in', ['confirm', 'validate', 'done']),
            ('planned_amount', '>', 0)
        ])
        
        total_budget = 0.0
        for line in budget_lines:
            line_start = max(line.date_from, start_date)
            line_end = min(line.date_to, end_date)
            
            if line_start <= line_end:
                line_days = (line.date_to - line.date_from).days + 1
                month_days = (line_end - line_start).days + 1
                proportion = month_days / line_days
                total_budget += line.planned_amount * proportion
        
        return total_budget
    
    def _get_monthly_data(self):
        current_year = datetime.now().year
        years_count = int(self.years_count)
        years = [current_year - years_count + 1 + i for i in range(years_count)]
        month_int = int(self.month)
        
        # Get all customers from invoices in the date range
        start_date = date(years[0], month_int, 1)
        end_date = (date(years[-1], month_int, 1) + relativedelta(months=1)) - relativedelta(days=1)
        
        domain = [
            ('move_type', '=', 'out_invoice'),
            ('state', '=', 'posted'),
            ('invoice_date', '>=', start_date),
            ('invoice_date', '<=', end_date)
        ]
        
        if self.company_ids:
            domain.append(('company_id', 'in', self.company_ids.ids))
        
        invoices = self.env['account.move'].sudo().search(domain)
        
        # Group by company and customer, then get amounts (actual or budget)
        company_data = {}
        processed_customers = set()
        
        for invoice in invoices:
            if not invoice.invoice_date or invoice.invoice_date.month != month_int:
                continue
            
            company = invoice.company_id.name
            customer = invoice.partner_id.name or invoice.partner_id.display_name or 'Unknown Customer'
            customer_key = (invoice.company_id.id, invoice.partner_id.id, customer)
            
            if company not in company_data:
                company_data[company] = {}
            if customer not in company_data[company]:
                company_data[company][customer] = {}
            
            if customer_key not in processed_customers:
                # Get amounts for all years (actual or budget)
                for year in years:
                    amount = self._get_customer_amount_for_month(
                        invoice.partner_id.id, invoice.company_id.id, year, month_int
                    )
                    company_data[company][customer][year] = amount
                
                processed_customers.add(customer_key)
        
        return {'years': years, 'companies': company_data}